name: Docker Build and Push to Docker Hub

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: darknet00/kii-react-zero-to-hero:latest
          build-args: |
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_INITIAL_PORT=${{ secrets.DB_INITIAL_PORT }}
            DB_DATABASE=${{ secrets.DB_DATABASE }}
            RUN_MIGRATIONS=${{ secrets.RUN_MIGRATIONS }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            REACT_APP_GOOGLE_CLIENT_ID=${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            BUHTIG_CLIENT_ID=${{ secrets.BUHTIG_CLIENT_ID }}
            BUHTIG_CLIENT_SECRET=${{ secrets.BUHTIG_CLIENT_SECRET }}
            REACT_APP_BUHTIG_CLIENT_ID=${{ secrets.REACT_APP_BUHTIG_CLIENT_ID }}
            GENERATE_SOURCEMAP=${{ secrets.GENERATE_SOURCEMAP }}
            MAIL_HOST=${{ secrets.MAIL_HOST }}
            MAIL_USER=${{ secrets.MAIL_USER }}
            MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
            MAIL_APP_PASSWORD=${{ secrets.MAIL_APP_PASSWORD }}
            PORT_NUMBER=${{ secrets.PORT_NUMBER }}
            NODE_ENV=${{ secrets.NODE_ENV }}
            MODE=${{ secrets.MODE }}
            REACT_APP_DISCORD_INVITE_URL=${{ secrets.REACT_APP_DISCORD_INVITE_URL }}
